# Generated by Django 4.0 on 2021-12-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='job',
        ),
    ]
