# Generated by Django 4.0 on 2021-12-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='local_name',
        ),
        migrations.AddField(
            model_name='host',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
