# Generated by Django 4.0 on 2021-12-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_carrer_host_career_host_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='local_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
