# Generated by Django 4.0 on 2021-12-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_host_local_description_host_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='phone_number',
            field=models.CharField(max_length=45),
        ),
        migrations.AddConstraint(
            model_name='host',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='unique_users_categories'),
        ),
    ]
