# Generated by Django 4.0 on 2021-12-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='talant',
            new_name='talent',
        ),
    ]
